// Generated by https://quicktype.io

export interface EvolutionChain {
  chain: Chain
  id: number
}

export interface Chain {
  evolution_details: EvolutionDetail[]
  evolves_to: Chain[]
  is_baby: boolean
  species: Species
}

export interface EvolutionDetail {
  min_level: number
  needs_overworld_rain: boolean
  time_of_day: string
  trigger: Species
  turn_upside_down: boolean
}

export interface Species {
  name: string
  url: string
}
